### ISSUE TITLE
Gear Bag Project: some JS errors

### ISSUE THREAD

**Issue by davidrans** [MooreGuy/gearbag#1]
When loading the page initially, I see this message logged:
`There was an error checking the gearbag.`

Then, when adding a device to the gear bag, I see these JS errors:
`Uncaught DataCloneError: Failed to execute 'add' on 'IDBObjectStore': An object could not be cloned.`
`Uncaught TypeError: Cannot read property 'removeClass' of undefined`

When removing an item from the gear bag, I see this error:
`Uncaught DataError: Failed to execute 'delete' on 'IDBObjectStore': The parameter is not a valid key.`

**Comment by g1y** [comment]
[Here is the pull request adressing this issue.](https://github.com/MooreGuy/gearbag/pull/2)

**Comment by g1y** [comment]
The TypeError and DataCloneErrors were caused because the requests were being passed data in a for in loop. For some reason it was adding a function to the end of the object and the add and delete methods were trying to add or delete the function after they had already added or deleted the object. That's why even though there was an error, the object was still added or deleted.

The TypeError was happening because of an element selector was returning undefined because the element it was looking for was already disposed.

Finally, the logged message was because a callback was checking for an error, but the function calling the callback was not passing it either a null value or an error.
